package com.guoguang.dksq.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ASSURE.
 */
public class Assure {

    private Long id;
    private String SeqNo;
    private String SerialNo="";
    private String CustomerID="";
    private String ContractType="";
    private String GuarantyType="";
    private String ContractStatus="";
    private String GuarantorID="";
    private String CertType="";
    private String CertID="";
    private String GuarantorName="";
    private String LoanCardNo="";
    private String GuarantyCurrency="";
    private String GuarantyValue="";
    private String GuarantyInfo="";
    private String OtherDescribe="";
    private String Remark="";
    private String InputUserID="";
    private String InputUserName="";
    private String InputOrgID="";
    private String InputOrgName="";
    private String InputDate="";
    private String UpdateDate="";

    public Assure() {
    }

    public Assure(Long id) {
        this.id = id;
    }

    public Assure(Long id, String SeqNo, String SerialNo, String CustomerID, String ContractType, String GuarantyType, String ContractStatus, String GuarantorID, String CertType, String CertID, String GuarantorName, String LoanCardNo, String GuarantyCurrency, String GuarantyValue, String GuarantyInfo, String OtherDescribe, String Remark, String InputUserID, String InputUserName, String InputOrgID, String InputOrgName, String InputDate, String UpdateDate) {
        this.id = id;
        this.SeqNo = SeqNo;
        this.SerialNo = SerialNo;
        this.CustomerID = CustomerID;
        this.ContractType = ContractType;
        this.GuarantyType = GuarantyType;
        this.ContractStatus = ContractStatus;
        this.GuarantorID = GuarantorID;
        this.CertType = CertType;
        this.CertID = CertID;
        this.GuarantorName = GuarantorName;
        this.LoanCardNo = LoanCardNo;
        this.GuarantyCurrency = GuarantyCurrency;
        this.GuarantyValue = GuarantyValue;
        this.GuarantyInfo = GuarantyInfo;
        this.OtherDescribe = OtherDescribe;
        this.Remark = Remark;
        this.InputUserID = InputUserID;
        this.InputUserName = InputUserName;
        this.InputOrgID = InputOrgID;
        this.InputOrgName = InputOrgName;
        this.InputDate = InputDate;
        this.UpdateDate = UpdateDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSeqNo() {
        return SeqNo;
    }

    public void setSeqNo(String SeqNo) {
        this.SeqNo = SeqNo;
    }

    public String getSerialNo() {
        return SerialNo;
    }

    public void setSerialNo(String SerialNo) {
        this.SerialNo = SerialNo;
    }

    public String getCustomerID() {
        return CustomerID;
    }

    public void setCustomerID(String CustomerID) {
        this.CustomerID = CustomerID;
    }

    public String getContractType() {
        return ContractType;
    }

    public void setContractType(String ContractType) {
        this.ContractType = ContractType;
    }

    public String getGuarantyType() {
        return GuarantyType;
    }

    public void setGuarantyType(String GuarantyType) {
        this.GuarantyType = GuarantyType;
    }

    public String getContractStatus() {
        return ContractStatus;
    }

    public void setContractStatus(String ContractStatus) {
        this.ContractStatus = ContractStatus;
    }

    public String getGuarantorID() {
        return GuarantorID;
    }

    public void setGuarantorID(String GuarantorID) {
        this.GuarantorID = GuarantorID;
    }

    public String getCertType() {
        return CertType;
    }

    public void setCertType(String CertType) {
        this.CertType = CertType;
    }

    public String getCertID() {
        return CertID;
    }

    public void setCertID(String CertID) {
        this.CertID = CertID;
    }

    public String getGuarantorName() {
        return GuarantorName;
    }

    public void setGuarantorName(String GuarantorName) {
        this.GuarantorName = GuarantorName;
    }

    public String getLoanCardNo() {
        return LoanCardNo;
    }

    public void setLoanCardNo(String LoanCardNo) {
        this.LoanCardNo = LoanCardNo;
    }

    public String getGuarantyCurrency() {
        return GuarantyCurrency;
    }

    public void setGuarantyCurrency(String GuarantyCurrency) {
        this.GuarantyCurrency = GuarantyCurrency;
    }

    public String getGuarantyValue() {
        return GuarantyValue;
    }

    public void setGuarantyValue(String GuarantyValue) {
        this.GuarantyValue = GuarantyValue;
    }

    public String getGuarantyInfo() {
        return GuarantyInfo;
    }

    public void setGuarantyInfo(String GuarantyInfo) {
        this.GuarantyInfo = GuarantyInfo;
    }

    public String getOtherDescribe() {
        return OtherDescribe;
    }

    public void setOtherDescribe(String OtherDescribe) {
        this.OtherDescribe = OtherDescribe;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getInputUserID() {
        return InputUserID;
    }

    public void setInputUserID(String InputUserID) {
        this.InputUserID = InputUserID;
    }

    public String getInputUserName() {
        return InputUserName;
    }

    public void setInputUserName(String InputUserName) {
        this.InputUserName = InputUserName;
    }

    public String getInputOrgID() {
        return InputOrgID;
    }

    public void setInputOrgID(String InputOrgID) {
        this.InputOrgID = InputOrgID;
    }

    public String getInputOrgName() {
        return InputOrgName;
    }

    public void setInputOrgName(String InputOrgName) {
        this.InputOrgName = InputOrgName;
    }

    public String getInputDate() {
        return InputDate;
    }

    public void setInputDate(String InputDate) {
        this.InputDate = InputDate;
    }

    public String getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(String UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

}
