package com.guoguang.dksq.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.guoguang.dksq.database.CodeLibDao;
import com.guoguang.dksq.database.AreaLibDao;
import com.guoguang.dksq.database.AssureDao;
import com.guoguang.dksq.database.LoanBusinessDao;
import com.guoguang.dksq.database.HouseDao;
import com.guoguang.dksq.database.LoanRecordDao;
import com.guoguang.dksq.database.PhotoEntityDao;
import com.guoguang.dksq.database.GuaranteeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CodeLibDao.createTable(db, ifNotExists);
        AreaLibDao.createTable(db, ifNotExists);
        AssureDao.createTable(db, ifNotExists);
        LoanBusinessDao.createTable(db, ifNotExists);
        HouseDao.createTable(db, ifNotExists);
        LoanRecordDao.createTable(db, ifNotExists);
        PhotoEntityDao.createTable(db, ifNotExists);
        GuaranteeDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CodeLibDao.dropTable(db, ifExists);
        AreaLibDao.dropTable(db, ifExists);
        AssureDao.dropTable(db, ifExists);
        LoanBusinessDao.dropTable(db, ifExists);
        HouseDao.dropTable(db, ifExists);
        LoanRecordDao.dropTable(db, ifExists);
        PhotoEntityDao.dropTable(db, ifExists);
        GuaranteeDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CodeLibDao.class);
        registerDaoClass(AreaLibDao.class);
        registerDaoClass(AssureDao.class);
        registerDaoClass(LoanBusinessDao.class);
        registerDaoClass(HouseDao.class);
        registerDaoClass(LoanRecordDao.class);
        registerDaoClass(PhotoEntityDao.class);
        registerDaoClass(GuaranteeDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
