package com.guoguang.dksq.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.guoguang.dksq.database.CodeLib;
import com.guoguang.dksq.database.AreaLib;
import com.guoguang.dksq.database.Assure;
import com.guoguang.dksq.database.LoanBusiness;
import com.guoguang.dksq.database.House;
import com.guoguang.dksq.database.LoanRecord;
import com.guoguang.dksq.database.PhotoEntity;
import com.guoguang.dksq.database.Guarantee;

import com.guoguang.dksq.database.CodeLibDao;
import com.guoguang.dksq.database.AreaLibDao;
import com.guoguang.dksq.database.AssureDao;
import com.guoguang.dksq.database.LoanBusinessDao;
import com.guoguang.dksq.database.HouseDao;
import com.guoguang.dksq.database.LoanRecordDao;
import com.guoguang.dksq.database.PhotoEntityDao;
import com.guoguang.dksq.database.GuaranteeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig codeLibDaoConfig;
    private final DaoConfig areaLibDaoConfig;
    private final DaoConfig assureDaoConfig;
    private final DaoConfig loanBusinessDaoConfig;
    private final DaoConfig houseDaoConfig;
    private final DaoConfig loanRecordDaoConfig;
    private final DaoConfig photoEntityDaoConfig;
    private final DaoConfig guaranteeDaoConfig;

    private final CodeLibDao codeLibDao;
    private final AreaLibDao areaLibDao;
    private final AssureDao assureDao;
    private final LoanBusinessDao loanBusinessDao;
    private final HouseDao houseDao;
    private final LoanRecordDao loanRecordDao;
    private final PhotoEntityDao photoEntityDao;
    private final GuaranteeDao guaranteeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        codeLibDaoConfig = daoConfigMap.get(CodeLibDao.class).clone();
        codeLibDaoConfig.initIdentityScope(type);

        areaLibDaoConfig = daoConfigMap.get(AreaLibDao.class).clone();
        areaLibDaoConfig.initIdentityScope(type);

        assureDaoConfig = daoConfigMap.get(AssureDao.class).clone();
        assureDaoConfig.initIdentityScope(type);

        loanBusinessDaoConfig = daoConfigMap.get(LoanBusinessDao.class).clone();
        loanBusinessDaoConfig.initIdentityScope(type);

        houseDaoConfig = daoConfigMap.get(HouseDao.class).clone();
        houseDaoConfig.initIdentityScope(type);

        loanRecordDaoConfig = daoConfigMap.get(LoanRecordDao.class).clone();
        loanRecordDaoConfig.initIdentityScope(type);

        photoEntityDaoConfig = daoConfigMap.get(PhotoEntityDao.class).clone();
        photoEntityDaoConfig.initIdentityScope(type);

        guaranteeDaoConfig = daoConfigMap.get(GuaranteeDao.class).clone();
        guaranteeDaoConfig.initIdentityScope(type);

        codeLibDao = new CodeLibDao(codeLibDaoConfig, this);
        areaLibDao = new AreaLibDao(areaLibDaoConfig, this);
        assureDao = new AssureDao(assureDaoConfig, this);
        loanBusinessDao = new LoanBusinessDao(loanBusinessDaoConfig, this);
        houseDao = new HouseDao(houseDaoConfig, this);
        loanRecordDao = new LoanRecordDao(loanRecordDaoConfig, this);
        photoEntityDao = new PhotoEntityDao(photoEntityDaoConfig, this);
        guaranteeDao = new GuaranteeDao(guaranteeDaoConfig, this);

        registerDao(CodeLib.class, codeLibDao);
        registerDao(AreaLib.class, areaLibDao);
        registerDao(Assure.class, assureDao);
        registerDao(LoanBusiness.class, loanBusinessDao);
        registerDao(House.class, houseDao);
        registerDao(LoanRecord.class, loanRecordDao);
        registerDao(PhotoEntity.class, photoEntityDao);
        registerDao(Guarantee.class, guaranteeDao);
    }
    
    public void clear() {
        codeLibDaoConfig.getIdentityScope().clear();
        areaLibDaoConfig.getIdentityScope().clear();
        assureDaoConfig.getIdentityScope().clear();
        loanBusinessDaoConfig.getIdentityScope().clear();
        houseDaoConfig.getIdentityScope().clear();
        loanRecordDaoConfig.getIdentityScope().clear();
        photoEntityDaoConfig.getIdentityScope().clear();
        guaranteeDaoConfig.getIdentityScope().clear();
    }

    public CodeLibDao getCodeLibDao() {
        return codeLibDao;
    }

    public AreaLibDao getAreaLibDao() {
        return areaLibDao;
    }

    public AssureDao getAssureDao() {
        return assureDao;
    }

    public LoanBusinessDao getLoanBusinessDao() {
        return loanBusinessDao;
    }

    public HouseDao getHouseDao() {
        return houseDao;
    }

    public LoanRecordDao getLoanRecordDao() {
        return loanRecordDao;
    }

    public PhotoEntityDao getPhotoEntityDao() {
        return photoEntityDao;
    }

    public GuaranteeDao getGuaranteeDao() {
        return guaranteeDao;
    }

}
