package com.guoguang.dksq.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.guoguang.dksq.database.Guarantee;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GUARANTEE.
*/
public class GuaranteeDao extends AbstractDao<Guarantee, Long> {

    public static final String TABLENAME = "GUARANTEE";

    /**
     * Properties of entity Guarantee.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SeqNo = new Property(1, String.class, "SeqNo", false, "SEQ_NO");
        public final static Property SerialNo = new Property(2, String.class, "SerialNo", false, "SERIAL_NO");
        public final static Property CustomerID = new Property(3, String.class, "CustomerID", false, "CUSTOMER_ID");
        public final static Property ContractType = new Property(4, String.class, "ContractType", false, "CONTRACT_TYPE");
        public final static Property GuarantyType = new Property(5, String.class, "GuarantyType", false, "GUARANTY_TYPE");
        public final static Property ContractStatus = new Property(6, String.class, "ContractStatus", false, "CONTRACT_STATUS");
        public final static Property GuarantorID = new Property(7, String.class, "GuarantorID", false, "GUARANTOR_ID");
        public final static Property CertType = new Property(8, String.class, "CertType", false, "CERT_TYPE");
        public final static Property CertID = new Property(9, String.class, "CertID", false, "CERT_ID");
        public final static Property GuarantorName = new Property(10, String.class, "GuarantorName", false, "GUARANTOR_NAME");
        public final static Property LoanCardNo = new Property(11, String.class, "LoanCardNo", false, "LOAN_CARD_NO");
        public final static Property GuarantyCurrency = new Property(12, String.class, "GuarantyCurrency", false, "GUARANTY_CURRENCY");
        public final static Property GuarantyValue = new Property(13, String.class, "GuarantyValue", false, "GUARANTY_VALUE");
        public final static Property GuarantyInfo = new Property(14, String.class, "GuarantyInfo", false, "GUARANTY_INFO");
        public final static Property OtherDescribe = new Property(15, String.class, "OtherDescribe", false, "OTHER_DESCRIBE");
        public final static Property Remark = new Property(16, String.class, "Remark", false, "REMARK");
        public final static Property GuaranteeForm = new Property(17, String.class, "GuaranteeForm", false, "GUARANTEE_FORM");
        public final static Property VouchWays = new Property(18, String.class, "VouchWays", false, "VOUCH_WAYS");
        public final static Property GuarantyStage = new Property(19, String.class, "GuarantyStage", false, "GUARANTY_STAGE");
        public final static Property ContractNo = new Property(20, String.class, "ContractNo", false, "CONTRACT_NO");
        public final static Property ContractSerialNo = new Property(21, String.class, "ContractSerialNo", false, "CONTRACT_SERIAL_NO");
        public final static Property CheckGuaranty = new Property(22, String.class, "CheckGuaranty", false, "CHECK_GUARANTY");
        public final static Property CheckGuarantyMan1 = new Property(23, String.class, "CheckGuarantyMan1", false, "CHECK_GUARANTY_MAN1");
        public final static Property BailAccount = new Property(24, String.class, "BailAccount", false, "BAIL_ACCOUNT");
        public final static Property SignDate = new Property(25, String.class, "SignDate", false, "SIGN_DATE");
        public final static Property BeginDate = new Property(26, String.class, "BeginDate", false, "BEGIN_DATE");
        public final static Property EndDate = new Property(27, String.class, "EndDate", false, "END_DATE");
        public final static Property GuarantyFreeType = new Property(28, String.class, "GuarantyFreeType", false, "GUARANTY_FREE_TYPE");
        public final static Property GuarantyData = new Property(29, String.class, "GuarantyData", false, "GUARANTY_DATA");
        public final static Property GuarantyDataName = new Property(30, String.class, "GuarantyDataName", false, "GUARANTY_DATA_NAME");
        public final static Property Reception = new Property(31, String.class, "Reception", false, "RECEPTION");
        public final static Property ReceptionDuty = new Property(32, String.class, "ReceptionDuty", false, "RECEPTION_DUTY");
    };


    public GuaranteeDao(DaoConfig config) {
        super(config);
    }
    
    public GuaranteeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GUARANTEE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SEQ_NO' TEXT," + // 1: SeqNo
                "'SERIAL_NO' TEXT," + // 2: SerialNo
                "'CUSTOMER_ID' TEXT," + // 3: CustomerID
                "'CONTRACT_TYPE' TEXT," + // 4: ContractType
                "'GUARANTY_TYPE' TEXT," + // 5: GuarantyType
                "'CONTRACT_STATUS' TEXT," + // 6: ContractStatus
                "'GUARANTOR_ID' TEXT," + // 7: GuarantorID
                "'CERT_TYPE' TEXT," + // 8: CertType
                "'CERT_ID' TEXT," + // 9: CertID
                "'GUARANTOR_NAME' TEXT," + // 10: GuarantorName
                "'LOAN_CARD_NO' TEXT," + // 11: LoanCardNo
                "'GUARANTY_CURRENCY' TEXT," + // 12: GuarantyCurrency
                "'GUARANTY_VALUE' TEXT," + // 13: GuarantyValue
                "'GUARANTY_INFO' TEXT," + // 14: GuarantyInfo
                "'OTHER_DESCRIBE' TEXT," + // 15: OtherDescribe
                "'REMARK' TEXT," + // 16: Remark
                "'GUARANTEE_FORM' TEXT," + // 17: GuaranteeForm
                "'VOUCH_WAYS' TEXT," + // 18: VouchWays
                "'GUARANTY_STAGE' TEXT," + // 19: GuarantyStage
                "'CONTRACT_NO' TEXT," + // 20: ContractNo
                "'CONTRACT_SERIAL_NO' TEXT," + // 21: ContractSerialNo
                "'CHECK_GUARANTY' TEXT," + // 22: CheckGuaranty
                "'CHECK_GUARANTY_MAN1' TEXT," + // 23: CheckGuarantyMan1
                "'BAIL_ACCOUNT' TEXT," + // 24: BailAccount
                "'SIGN_DATE' TEXT," + // 25: SignDate
                "'BEGIN_DATE' TEXT," + // 26: BeginDate
                "'END_DATE' TEXT," + // 27: EndDate
                "'GUARANTY_FREE_TYPE' TEXT," + // 28: GuarantyFreeType
                "'GUARANTY_DATA' TEXT," + // 29: GuarantyData
                "'GUARANTY_DATA_NAME' TEXT," + // 30: GuarantyDataName
                "'RECEPTION' TEXT," + // 31: Reception
                "'RECEPTION_DUTY' TEXT);"); // 32: ReceptionDuty
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GUARANTEE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Guarantee entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String SeqNo = entity.getSeqNo();
        if (SeqNo != null) {
            stmt.bindString(2, SeqNo);
        }
 
        String SerialNo = entity.getSerialNo();
        if (SerialNo != null) {
            stmt.bindString(3, SerialNo);
        }
 
        String CustomerID = entity.getCustomerID();
        if (CustomerID != null) {
            stmt.bindString(4, CustomerID);
        }
 
        String ContractType = entity.getContractType();
        if (ContractType != null) {
            stmt.bindString(5, ContractType);
        }
 
        String GuarantyType = entity.getGuarantyType();
        if (GuarantyType != null) {
            stmt.bindString(6, GuarantyType);
        }
 
        String ContractStatus = entity.getContractStatus();
        if (ContractStatus != null) {
            stmt.bindString(7, ContractStatus);
        }
 
        String GuarantorID = entity.getGuarantorID();
        if (GuarantorID != null) {
            stmt.bindString(8, GuarantorID);
        }
 
        String CertType = entity.getCertType();
        if (CertType != null) {
            stmt.bindString(9, CertType);
        }
 
        String CertID = entity.getCertID();
        if (CertID != null) {
            stmt.bindString(10, CertID);
        }
 
        String GuarantorName = entity.getGuarantorName();
        if (GuarantorName != null) {
            stmt.bindString(11, GuarantorName);
        }
 
        String LoanCardNo = entity.getLoanCardNo();
        if (LoanCardNo != null) {
            stmt.bindString(12, LoanCardNo);
        }
 
        String GuarantyCurrency = entity.getGuarantyCurrency();
        if (GuarantyCurrency != null) {
            stmt.bindString(13, GuarantyCurrency);
        }
 
        String GuarantyValue = entity.getGuarantyValue();
        if (GuarantyValue != null) {
            stmt.bindString(14, GuarantyValue);
        }
 
        String GuarantyInfo = entity.getGuarantyInfo();
        if (GuarantyInfo != null) {
            stmt.bindString(15, GuarantyInfo);
        }
 
        String OtherDescribe = entity.getOtherDescribe();
        if (OtherDescribe != null) {
            stmt.bindString(16, OtherDescribe);
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(17, Remark);
        }
 
        String GuaranteeForm = entity.getGuaranteeForm();
        if (GuaranteeForm != null) {
            stmt.bindString(18, GuaranteeForm);
        }
 
        String VouchWays = entity.getVouchWays();
        if (VouchWays != null) {
            stmt.bindString(19, VouchWays);
        }
 
        String GuarantyStage = entity.getGuarantyStage();
        if (GuarantyStage != null) {
            stmt.bindString(20, GuarantyStage);
        }
 
        String ContractNo = entity.getContractNo();
        if (ContractNo != null) {
            stmt.bindString(21, ContractNo);
        }
 
        String ContractSerialNo = entity.getContractSerialNo();
        if (ContractSerialNo != null) {
            stmt.bindString(22, ContractSerialNo);
        }
 
        String CheckGuaranty = entity.getCheckGuaranty();
        if (CheckGuaranty != null) {
            stmt.bindString(23, CheckGuaranty);
        }
 
        String CheckGuarantyMan1 = entity.getCheckGuarantyMan1();
        if (CheckGuarantyMan1 != null) {
            stmt.bindString(24, CheckGuarantyMan1);
        }
 
        String BailAccount = entity.getBailAccount();
        if (BailAccount != null) {
            stmt.bindString(25, BailAccount);
        }
 
        String SignDate = entity.getSignDate();
        if (SignDate != null) {
            stmt.bindString(26, SignDate);
        }
 
        String BeginDate = entity.getBeginDate();
        if (BeginDate != null) {
            stmt.bindString(27, BeginDate);
        }
 
        String EndDate = entity.getEndDate();
        if (EndDate != null) {
            stmt.bindString(28, EndDate);
        }
 
        String GuarantyFreeType = entity.getGuarantyFreeType();
        if (GuarantyFreeType != null) {
            stmt.bindString(29, GuarantyFreeType);
        }
 
        String GuarantyData = entity.getGuarantyData();
        if (GuarantyData != null) {
            stmt.bindString(30, GuarantyData);
        }
 
        String GuarantyDataName = entity.getGuarantyDataName();
        if (GuarantyDataName != null) {
            stmt.bindString(31, GuarantyDataName);
        }
 
        String Reception = entity.getReception();
        if (Reception != null) {
            stmt.bindString(32, Reception);
        }
 
        String ReceptionDuty = entity.getReceptionDuty();
        if (ReceptionDuty != null) {
            stmt.bindString(33, ReceptionDuty);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Guarantee readEntity(Cursor cursor, int offset) {
        Guarantee entity = new Guarantee( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // SeqNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // SerialNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // CustomerID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ContractType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // GuarantyType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ContractStatus
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // GuarantorID
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // CertType
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // CertID
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // GuarantorName
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // LoanCardNo
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // GuarantyCurrency
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // GuarantyValue
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // GuarantyInfo
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // OtherDescribe
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // Remark
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // GuaranteeForm
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // VouchWays
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // GuarantyStage
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // ContractNo
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // ContractSerialNo
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // CheckGuaranty
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // CheckGuarantyMan1
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // BailAccount
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // SignDate
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // BeginDate
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // EndDate
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // GuarantyFreeType
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // GuarantyData
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // GuarantyDataName
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // Reception
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32) // ReceptionDuty
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Guarantee entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSeqNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSerialNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCustomerID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContractType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGuarantyType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setContractStatus(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGuarantorID(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCertType(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCertID(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGuarantorName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLoanCardNo(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setGuarantyCurrency(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGuarantyValue(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setGuarantyInfo(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setOtherDescribe(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRemark(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setGuaranteeForm(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setVouchWays(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setGuarantyStage(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setContractNo(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setContractSerialNo(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setCheckGuaranty(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setCheckGuarantyMan1(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setBailAccount(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setSignDate(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setBeginDate(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setEndDate(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setGuarantyFreeType(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setGuarantyData(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setGuarantyDataName(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setReception(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setReceptionDuty(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Guarantee entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Guarantee entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
