package com.guoguang.dksq.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GUARANTEE.
 */
public class Guarantee {

    private Long id;
    private String SeqNo ="";
    private String SerialNo="";
    private String CustomerID="";
    private String ContractType="";
    private String GuarantyType="";
    private String ContractStatus="";
    private String GuarantorID="";
    private String CertType="";
    private String CertID="";
    private String GuarantorName="";
    private String LoanCardNo="";
    private String GuarantyCurrency="";
    private String GuarantyValue="";
    private String GuarantyInfo="";
    private String OtherDescribe="";
    private String Remark="";
    private String GuaranteeForm="";
    private String VouchWays="";
    private String GuarantyStage="";
    private String ContractNo="";
    private String ContractSerialNo="";
    private String CheckGuaranty="";
    private String CheckGuarantyMan1="";
    private String BailAccount="";
    private String SignDate="";
    private String BeginDate="";
    private String EndDate="";
    private String GuarantyFreeType="";
    private String GuarantyData="";
    private String GuarantyDataName="";
    private String Reception="";
    private String ReceptionDuty="";

    public Guarantee() {
    }

    public Guarantee(Long id) {
        this.id = id;
    }

    public Guarantee(Long id, String SeqNo, String SerialNo, String CustomerID, String ContractType, String GuarantyType, String ContractStatus, String GuarantorID, String CertType, String CertID, String GuarantorName, String LoanCardNo, String GuarantyCurrency, String GuarantyValue, String GuarantyInfo, String OtherDescribe, String Remark, String GuaranteeForm, String VouchWays, String GuarantyStage, String ContractNo, String ContractSerialNo, String CheckGuaranty, String CheckGuarantyMan1, String BailAccount, String SignDate, String BeginDate, String EndDate, String GuarantyFreeType, String GuarantyData, String GuarantyDataName, String Reception, String ReceptionDuty) {
        this.id = id;
        this.SeqNo = SeqNo;
        this.SerialNo = SerialNo;
        this.CustomerID = CustomerID;
        this.ContractType = ContractType;
        this.GuarantyType = GuarantyType;
        this.ContractStatus = ContractStatus;
        this.GuarantorID = GuarantorID;
        this.CertType = CertType;
        this.CertID = CertID;
        this.GuarantorName = GuarantorName;
        this.LoanCardNo = LoanCardNo;
        this.GuarantyCurrency = GuarantyCurrency;
        this.GuarantyValue = GuarantyValue;
        this.GuarantyInfo = GuarantyInfo;
        this.OtherDescribe = OtherDescribe;
        this.Remark = Remark;
        this.GuaranteeForm = GuaranteeForm;
        this.VouchWays = VouchWays;
        this.GuarantyStage = GuarantyStage;
        this.ContractNo = ContractNo;
        this.ContractSerialNo = ContractSerialNo;
        this.CheckGuaranty = CheckGuaranty;
        this.CheckGuarantyMan1 = CheckGuarantyMan1;
        this.BailAccount = BailAccount;
        this.SignDate = SignDate;
        this.BeginDate = BeginDate;
        this.EndDate = EndDate;
        this.GuarantyFreeType = GuarantyFreeType;
        this.GuarantyData = GuarantyData;
        this.GuarantyDataName = GuarantyDataName;
        this.Reception = Reception;
        this.ReceptionDuty = ReceptionDuty;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSeqNo() {
        return SeqNo;
    }

    public void setSeqNo(String SeqNo) {
        this.SeqNo = SeqNo;
    }

    public String getSerialNo() {
        return SerialNo;
    }

    public void setSerialNo(String SerialNo) {
        this.SerialNo = SerialNo;
    }

    public String getCustomerID() {
        return CustomerID;
    }

    public void setCustomerID(String CustomerID) {
        this.CustomerID = CustomerID;
    }

    public String getContractType() {
        return ContractType;
    }

    public void setContractType(String ContractType) {
        this.ContractType = ContractType;
    }

    public String getGuarantyType() {
        return GuarantyType;
    }

    public void setGuarantyType(String GuarantyType) {
        this.GuarantyType = GuarantyType;
    }

    public String getContractStatus() {
        return ContractStatus;
    }

    public void setContractStatus(String ContractStatus) {
        this.ContractStatus = ContractStatus;
    }

    public String getGuarantorID() {
        return GuarantorID;
    }

    public void setGuarantorID(String GuarantorID) {
        this.GuarantorID = GuarantorID;
    }

    public String getCertType() {
        return CertType;
    }

    public void setCertType(String CertType) {
        this.CertType = CertType;
    }

    public String getCertID() {
        return CertID;
    }

    public void setCertID(String CertID) {
        this.CertID = CertID;
    }

    public String getGuarantorName() {
        return GuarantorName;
    }

    public void setGuarantorName(String GuarantorName) {
        this.GuarantorName = GuarantorName;
    }

    public String getLoanCardNo() {
        return LoanCardNo;
    }

    public void setLoanCardNo(String LoanCardNo) {
        this.LoanCardNo = LoanCardNo;
    }

    public String getGuarantyCurrency() {
        return GuarantyCurrency;
    }

    public void setGuarantyCurrency(String GuarantyCurrency) {
        this.GuarantyCurrency = GuarantyCurrency;
    }

    public String getGuarantyValue() {
        return GuarantyValue;
    }

    public void setGuarantyValue(String GuarantyValue) {
        this.GuarantyValue = GuarantyValue;
    }

    public String getGuarantyInfo() {
        return GuarantyInfo;
    }

    public void setGuarantyInfo(String GuarantyInfo) {
        this.GuarantyInfo = GuarantyInfo;
    }

    public String getOtherDescribe() {
        return OtherDescribe;
    }

    public void setOtherDescribe(String OtherDescribe) {
        this.OtherDescribe = OtherDescribe;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getGuaranteeForm() {
        return GuaranteeForm;
    }

    public void setGuaranteeForm(String GuaranteeForm) {
        this.GuaranteeForm = GuaranteeForm;
    }

    public String getVouchWays() {
        return VouchWays;
    }

    public void setVouchWays(String VouchWays) {
        this.VouchWays = VouchWays;
    }

    public String getGuarantyStage() {
        return GuarantyStage;
    }

    public void setGuarantyStage(String GuarantyStage) {
        this.GuarantyStage = GuarantyStage;
    }

    public String getContractNo() {
        return ContractNo;
    }

    public void setContractNo(String ContractNo) {
        this.ContractNo = ContractNo;
    }

    public String getContractSerialNo() {
        return ContractSerialNo;
    }

    public void setContractSerialNo(String ContractSerialNo) {
        this.ContractSerialNo = ContractSerialNo;
    }

    public String getCheckGuaranty() {
        return CheckGuaranty;
    }

    public void setCheckGuaranty(String CheckGuaranty) {
        this.CheckGuaranty = CheckGuaranty;
    }

    public String getCheckGuarantyMan1() {
        return CheckGuarantyMan1;
    }

    public void setCheckGuarantyMan1(String CheckGuarantyMan1) {
        this.CheckGuarantyMan1 = CheckGuarantyMan1;
    }

    public String getBailAccount() {
        return BailAccount;
    }

    public void setBailAccount(String BailAccount) {
        this.BailAccount = BailAccount;
    }

    public String getSignDate() {
        return SignDate;
    }

    public void setSignDate(String SignDate) {
        this.SignDate = SignDate;
    }

    public String getBeginDate() {
        return BeginDate;
    }

    public void setBeginDate(String BeginDate) {
        this.BeginDate = BeginDate;
    }

    public String getEndDate() {
        return EndDate;
    }

    public void setEndDate(String EndDate) {
        this.EndDate = EndDate;
    }

    public String getGuarantyFreeType() {
        return GuarantyFreeType;
    }

    public void setGuarantyFreeType(String GuarantyFreeType) {
        this.GuarantyFreeType = GuarantyFreeType;
    }

    public String getGuarantyData() {
        return GuarantyData;
    }

    public void setGuarantyData(String GuarantyData) {
        this.GuarantyData = GuarantyData;
    }

    public String getGuarantyDataName() {
        return GuarantyDataName;
    }

    public void setGuarantyDataName(String GuarantyDataName) {
        this.GuarantyDataName = GuarantyDataName;
    }

    public String getReception() {
        return Reception;
    }

    public void setReception(String Reception) {
        this.Reception = Reception;
    }

    public String getReceptionDuty() {
        return ReceptionDuty;
    }

    public void setReceptionDuty(String ReceptionDuty) {
        this.ReceptionDuty = ReceptionDuty;
    }

}
