package com.guoguang.dksq.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOUSE.
 */
public class House {

    private Long id;
    private String SeqNo;
    private String GuarantyID="";
    private String ConfirmNum="";
    private String rukuname1="";
    private String rukucode1="";
    private String rukuname2="";
    private String rukucode2="";
    private String rukuname3="";
    private String rukucode3="";
    private String GuarantyType="";
    private String CertType="";
    private String CertID="";
    private String OwnerID="";
    private String OwnerName="";
    private String LoanCardNo="";
    private String OwnerType="";
    private String Togetheronwer="";
    private String GuarantyRightID="";
    private String GuarantyTerm="";
    private String GuarantySubType="";
    private String HourseFormat="";
    private String HouseName="";
    private String Developer="";
    private String DeveloperVouch="";
    private String BuildingName="";
    private String FloorNum="";
    private String GuarantyLocation="";
    private String GuarantyArea="";
    private String UnitPrice="";
    private String GuarantyAmount="";
    private String BuyMoney="";
    private String MustPayMoney="";
    private String AlreadPayMoney="";
    private String FirstPaySource="";
    private String BuildingFinishDate="";
    private String FitmentState="";
    private String UseNature="";
    private String GuarantyDescribe3="";
    private String ThirdParty1="";
    private String Frequency="";
    private String GuarantyDescript="";
    private String EvalMethod="";
    private String EvalOrgName="";
    private String EvalOrgID="";
    private String EvalDate="";
    private String EvalCurrency="";
    private String EvalNetValue="";
    private String EvalNetValue2="";
    private String GuarantyCurrency="";
    private String ConfirmValue="";
    private String EvalSignValue="";
    private String ConfirmSignValue="";
    private String BusSignVale="";
    private String BusTotalVale="";
    private String OtherGuarantyRight="";
    private String OldOwner="";
    private String BusBuyContractNo="";
    private String Remark="";
    private String InputUserID="";
    private String InputOrgID="";
    private String InputDate="";
    private String UpdateDate="";
    private String GuarantyAreaName="";
    public House() {
    }

    public House(Long id) {
        this.id = id;
    }

    public House(Long id, String SeqNo, String GuarantyID, String ConfirmNum, String rukuname1, String rukucode1, String rukuname2, String rukucode2, String rukuname3, String rukucode3, String GuarantyType, String CertType, String CertID, String OwnerID, String OwnerName, String LoanCardNo, String OwnerType, String Togetheronwer, String GuarantyRightID, String GuarantyTerm, String GuarantySubType, String HourseFormat, String HouseName, String Developer, String DeveloperVouch, String BuildingName, String FloorNum, String GuarantyLocation, String GuarantyArea, String UnitPrice, String GuarantyAmount, String BuyMoney, String MustPayMoney, String AlreadPayMoney, String FirstPaySource, String BuildingFinishDate, String FitmentState, String UseNature, String GuarantyDescribe3, String ThirdParty1, String Frequency, String GuarantyDescript, String EvalMethod, String EvalOrgName, String EvalOrgID, String EvalDate, String EvalCurrency, String EvalNetValue, String EvalNetValue2, String GuarantyCurrency, String ConfirmValue, String EvalSignValue, String ConfirmSignValue, String BusSignVale, String BusTotalVale, String OtherGuarantyRight, String OldOwner, String BusBuyContractNo, String Remark, String InputUserID, String InputOrgID, String InputDate, String UpdateDate,String GuarantyAreaName) {
        this.id = id;
        this.SeqNo = SeqNo;
        this.GuarantyID = GuarantyID;
        this.ConfirmNum = ConfirmNum;
        this.rukuname1 = rukuname1;
        this.rukucode1 = rukucode1;
        this.rukuname2 = rukuname2;
        this.rukucode2 = rukucode2;
        this.rukuname3 = rukuname3;
        this.rukucode3 = rukucode3;
        this.GuarantyType = GuarantyType;
        this.CertType = CertType;
        this.CertID = CertID;
        this.OwnerID = OwnerID;
        this.OwnerName = OwnerName;
        this.LoanCardNo = LoanCardNo;
        this.OwnerType = OwnerType;
        this.Togetheronwer = Togetheronwer;
        this.GuarantyRightID = GuarantyRightID;
        this.GuarantyTerm = GuarantyTerm;
        this.GuarantySubType = GuarantySubType;
        this.HourseFormat = HourseFormat;
        this.HouseName = HouseName;
        this.Developer = Developer;
        this.DeveloperVouch = DeveloperVouch;
        this.BuildingName = BuildingName;
        this.FloorNum = FloorNum;
        this.GuarantyLocation = GuarantyLocation;
        this.GuarantyArea = GuarantyArea;
        this.UnitPrice = UnitPrice;
        this.GuarantyAmount = GuarantyAmount;
        this.BuyMoney = BuyMoney;
        this.MustPayMoney = MustPayMoney;
        this.AlreadPayMoney = AlreadPayMoney;
        this.FirstPaySource = FirstPaySource;
        this.BuildingFinishDate = BuildingFinishDate;
        this.FitmentState = FitmentState;
        this.UseNature = UseNature;
        this.GuarantyDescribe3 = GuarantyDescribe3;
        this.ThirdParty1 = ThirdParty1;
        this.Frequency = Frequency;
        this.GuarantyDescript = GuarantyDescript;
        this.EvalMethod = EvalMethod;
        this.EvalOrgName = EvalOrgName;
        this.EvalOrgID = EvalOrgID;
        this.EvalDate = EvalDate;
        this.EvalCurrency = EvalCurrency;
        this.EvalNetValue = EvalNetValue;
        this.EvalNetValue2 = EvalNetValue2;
        this.GuarantyCurrency = GuarantyCurrency;
        this.ConfirmValue = ConfirmValue;
        this.EvalSignValue = EvalSignValue;
        this.ConfirmSignValue = ConfirmSignValue;
        this.BusSignVale = BusSignVale;
        this.BusTotalVale = BusTotalVale;
        this.OtherGuarantyRight = OtherGuarantyRight;
        this.OldOwner = OldOwner;
        this.BusBuyContractNo = BusBuyContractNo;
        this.Remark = Remark;
        this.InputUserID = InputUserID;
        this.InputOrgID = InputOrgID;
        this.InputDate = InputDate;
        this.UpdateDate = UpdateDate;
        this.GuarantyAreaName = GuarantyAreaName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSeqNo() {
        return SeqNo;
    }

    public void setSeqNo(String SeqNo) {
        this.SeqNo = SeqNo;
    }

    public String getGuarantyID() {
        return GuarantyID;
    }

    public void setGuarantyID(String GuarantyID) {
        this.GuarantyID = GuarantyID;
    }

    public String getConfirmNum() {
        return ConfirmNum;
    }

    public void setConfirmNum(String ConfirmNum) {
        this.ConfirmNum = ConfirmNum;
    }

    public String getRukuname1() {
        return rukuname1;
    }

    public void setRukuname1(String rukuname1) {
        this.rukuname1 = rukuname1;
    }

    public String getRukucode1() {
        return rukucode1;
    }

    public void setRukucode1(String rukucode1) {
        this.rukucode1 = rukucode1;
    }

    public String getRukuname2() {
        return rukuname2;
    }

    public void setRukuname2(String rukuname2) {
        this.rukuname2 = rukuname2;
    }

    public String getRukucode2() {
        return rukucode2;
    }

    public void setRukucode2(String rukucode2) {
        this.rukucode2 = rukucode2;
    }

    public String getRukuname3() {
        return rukuname3;
    }

    public void setRukuname3(String rukuname3) {
        this.rukuname3 = rukuname3;
    }

    public String getRukucode3() {
        return rukucode3;
    }

    public void setRukucode3(String rukucode3) {
        this.rukucode3 = rukucode3;
    }

    public String getGuarantyType() {
        return GuarantyType;
    }

    public void setGuarantyType(String GuarantyType) {
        this.GuarantyType = GuarantyType;
    }

    public String getCertType() {
        return CertType;
    }

    public void setCertType(String CertType) {
        this.CertType = CertType;
    }

    public String getCertID() {
        return CertID;
    }

    public void setCertID(String CertID) {
        this.CertID = CertID;
    }

    public String getOwnerID() {
        return OwnerID;
    }

    public void setOwnerID(String OwnerID) {
        this.OwnerID = OwnerID;
    }

    public String getOwnerName() {
        return OwnerName;
    }

    public void setOwnerName(String OwnerName) {
        this.OwnerName = OwnerName;
    }

    public String getLoanCardNo() {
        return LoanCardNo;
    }

    public void setLoanCardNo(String LoanCardNo) {
        this.LoanCardNo = LoanCardNo;
    }

    public String getOwnerType() {
        return OwnerType;
    }

    public void setOwnerType(String OwnerType) {
        this.OwnerType = OwnerType;
    }

    public String getTogetheronwer() {
        return Togetheronwer;
    }

    public void setTogetheronwer(String Togetheronwer) {
        this.Togetheronwer = Togetheronwer;
    }

    public String getGuarantyRightID() {
        return GuarantyRightID;
    }

    public void setGuarantyRightID(String GuarantyRightID) {
        this.GuarantyRightID = GuarantyRightID;
    }

    public String getGuarantyTerm() {
        return GuarantyTerm;
    }

    public void setGuarantyTerm(String GuarantyTerm) {
        this.GuarantyTerm = GuarantyTerm;
    }

    public String getGuarantySubType() {
        return GuarantySubType;
    }

    public void setGuarantySubType(String GuarantySubType) {
        this.GuarantySubType = GuarantySubType;
    }

    public String getHourseFormat() {
        return HourseFormat;
    }

    public void setHourseFormat(String HourseFormat) {
        this.HourseFormat = HourseFormat;
    }

    public String getHouseName() {
        return HouseName;
    }

    public void setHouseName(String HouseName) {
        this.HouseName = HouseName;
    }

    public String getDeveloper() {
        return Developer;
    }

    public void setDeveloper(String Developer) {
        this.Developer = Developer;
    }

    public String getDeveloperVouch() {
        return DeveloperVouch;
    }

    public void setDeveloperVouch(String DeveloperVouch) {
        this.DeveloperVouch = DeveloperVouch;
    }

    public String getBuildingName() {
        return BuildingName;
    }

    public void setBuildingName(String BuildingName) {
        this.BuildingName = BuildingName;
    }

    public String getFloorNum() {
        return FloorNum;
    }

    public void setFloorNum(String FloorNum) {
        this.FloorNum = FloorNum;
    }

    public String getGuarantyLocation() {
        return GuarantyLocation;
    }

    public void setGuarantyLocation(String GuarantyLocation) {
        this.GuarantyLocation = GuarantyLocation;
    }

    public String getGuarantyArea() {
        return GuarantyArea;
    }

    public void setGuarantyArea(String GuarantyArea) {
        this.GuarantyArea = GuarantyArea;
    }

    public String getUnitPrice() {
        return UnitPrice;
    }

    public void setUnitPrice(String UnitPrice) {
        this.UnitPrice = UnitPrice;
    }

    public String getGuarantyAmount() {
        return GuarantyAmount;
    }

    public void setGuarantyAmount(String GuarantyAmount) {
        this.GuarantyAmount = GuarantyAmount;
    }

    public String getBuyMoney() {
        return BuyMoney;
    }

    public void setBuyMoney(String BuyMoney) {
        this.BuyMoney = BuyMoney;
    }

    public String getMustPayMoney() {
        return MustPayMoney;
    }

    public void setMustPayMoney(String MustPayMoney) {
        this.MustPayMoney = MustPayMoney;
    }

    public String getAlreadPayMoney() {
        return AlreadPayMoney;
    }

    public void setAlreadPayMoney(String AlreadPayMoney) {
        this.AlreadPayMoney = AlreadPayMoney;
    }

    public String getFirstPaySource() {
        return FirstPaySource;
    }

    public void setFirstPaySource(String FirstPaySource) {
        this.FirstPaySource = FirstPaySource;
    }

    public String getBuildingFinishDate() {
        return BuildingFinishDate;
    }

    public void setBuildingFinishDate(String BuildingFinishDate) {
        this.BuildingFinishDate = BuildingFinishDate;
    }

    public String getFitmentState() {
        return FitmentState;
    }

    public void setFitmentState(String FitmentState) {
        this.FitmentState = FitmentState;
    }

    public String getUseNature() {
        return UseNature;
    }

    public void setUseNature(String UseNature) {
        this.UseNature = UseNature;
    }

    public String getGuarantyDescribe3() {
        return GuarantyDescribe3;
    }

    public void setGuarantyDescribe3(String GuarantyDescribe3) {
        this.GuarantyDescribe3 = GuarantyDescribe3;
    }

    public String getThirdParty1() {
        return ThirdParty1;
    }

    public void setThirdParty1(String ThirdParty1) {
        this.ThirdParty1 = ThirdParty1;
    }

    public String getFrequency() {
        return Frequency;
    }

    public void setFrequency(String Frequency) {
        this.Frequency = Frequency;
    }

    public String getGuarantyDescript() {
        return GuarantyDescript;
    }

    public void setGuarantyDescript(String GuarantyDescript) {
        this.GuarantyDescript = GuarantyDescript;
    }

    public String getEvalMethod() {
        return EvalMethod;
    }

    public void setEvalMethod(String EvalMethod) {
        this.EvalMethod = EvalMethod;
    }

    public String getEvalOrgName() {
        return EvalOrgName;
    }

    public void setEvalOrgName(String EvalOrgName) {
        this.EvalOrgName = EvalOrgName;
    }

    public String getEvalOrgID() {
        return EvalOrgID;
    }

    public void setEvalOrgID(String EvalOrgID) {
        this.EvalOrgID = EvalOrgID;
    }

    public String getEvalDate() {
        return EvalDate;
    }

    public void setEvalDate(String EvalDate) {
        this.EvalDate = EvalDate;
    }

    public String getEvalCurrency() {
        return EvalCurrency;
    }

    public void setEvalCurrency(String EvalCurrency) {
        this.EvalCurrency = EvalCurrency;
    }

    public String getEvalNetValue() {
        return EvalNetValue;
    }

    public void setEvalNetValue(String EvalNetValue) {
        this.EvalNetValue = EvalNetValue;
    }

    public String getEvalNetValue2() {
        return EvalNetValue2;
    }

    public void setEvalNetValue2(String EvalNetValue2) {
        this.EvalNetValue2 = EvalNetValue2;
    }

    public String getGuarantyCurrency() {
        return GuarantyCurrency;
    }

    public void setGuarantyCurrency(String GuarantyCurrency) {
        this.GuarantyCurrency = GuarantyCurrency;
    }

    public String getConfirmValue() {
        return ConfirmValue;
    }

    public void setConfirmValue(String ConfirmValue) {
        this.ConfirmValue = ConfirmValue;
    }

    public String getEvalSignValue() {
        return EvalSignValue;
    }

    public void setEvalSignValue(String EvalSignValue) {
        this.EvalSignValue = EvalSignValue;
    }

    public String getConfirmSignValue() {
        return ConfirmSignValue;
    }

    public void setConfirmSignValue(String ConfirmSignValue) {
        this.ConfirmSignValue = ConfirmSignValue;
    }

    public String getBusSignVale() {
        return BusSignVale;
    }

    public void setBusSignVale(String BusSignVale) {
        this.BusSignVale = BusSignVale;
    }

    public String getBusTotalVale() {
        return BusTotalVale;
    }

    public void setBusTotalVale(String BusTotalVale) {
        this.BusTotalVale = BusTotalVale;
    }

    public String getOtherGuarantyRight() {
        return OtherGuarantyRight;
    }

    public void setOtherGuarantyRight(String OtherGuarantyRight) {
        this.OtherGuarantyRight = OtherGuarantyRight;
    }

    public String getOldOwner() {
        return OldOwner;
    }

    public void setOldOwner(String OldOwner) {
        this.OldOwner = OldOwner;
    }

    public String getBusBuyContractNo() {
        return BusBuyContractNo;
    }

    public void setBusBuyContractNo(String BusBuyContractNo) {
        this.BusBuyContractNo = BusBuyContractNo;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getInputUserID() {
        return InputUserID;
    }

    public void setInputUserID(String InputUserID) {
        this.InputUserID = InputUserID;
    }

    public String getInputOrgID() {
        return InputOrgID;
    }

    public void setInputOrgID(String InputOrgID) {
        this.InputOrgID = InputOrgID;
    }

    public String getInputDate() {
        return InputDate;
    }

    public void setInputDate(String InputDate) {
        this.InputDate = InputDate;
    }

    public String getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(String UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public String getGuarantyAreaName() {
        return GuarantyAreaName;
    }

    public void setGuarantyAreaName(String guarantyAreaName) {
        GuarantyAreaName = guarantyAreaName;
    }
}
