package com.guoguang.dksq.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOAN_RECORD.
 */
public class LoanRecord {

    private Long id;
    private String SeqNo;
    private String CustomerName;
    private String CustomerID;
    private String BusinessType;
    private String ContractFlag;
    private String UpdateTime;
    private String InputUserID;
    private String InputUserName;

    private boolean deltag;

    public boolean isDeltag() {
        return deltag;
    }

    public void setDeltag(boolean deltag) {
        this.deltag = deltag;
    }

    public LoanRecord() {
    }

    public LoanRecord(Long id) {
        this.id = id;
    }

    public LoanRecord(Long id, String SeqNo, String CustomerName, String CustomerID, String BusinessType, String ContractFlag, String UpdateTime, String InputUserID, String InputUserName) {
        this.id = id;
        this.SeqNo = SeqNo;
        this.CustomerName = CustomerName;
        this.CustomerID = CustomerID;
        this.BusinessType = BusinessType;
        this.ContractFlag = ContractFlag;
        this.UpdateTime = UpdateTime;
        this.InputUserID = InputUserID;
        this.InputUserName = InputUserName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSeqNo() {
        return SeqNo;
    }

    public void setSeqNo(String SeqNo) {
        this.SeqNo = SeqNo;
    }

    public String getCustomerName() {
        return CustomerName;
    }

    public void setCustomerName(String CustomerName) {
        this.CustomerName = CustomerName;
    }

    public String getCustomerID() {
        return CustomerID;
    }

    public void setCustomerID(String CustomerID) {
        this.CustomerID = CustomerID;
    }

    public String getBusinessType() {
        return BusinessType;
    }

    public void setBusinessType(String BusinessType) {
        this.BusinessType = BusinessType;
    }

    public String getContractFlag() {
        return ContractFlag;
    }

    public void setContractFlag(String ContractFlag) {
        this.ContractFlag = ContractFlag;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getInputUserID() {
        return InputUserID;
    }

    public void setInputUserID(String InputUserID) {
        this.InputUserID = InputUserID;
    }

    public String getInputUserName() {
        return InputUserName;
    }

    public void setInputUserName(String InputUserName) {
        this.InputUserName = InputUserName;
    }

}
