package com.guoguang.dksq.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PHOTO_ENTITY.
 */
public class PhotoEntity {

    private Long id;
    private Boolean isBp;
    private String SeqNo;
    private String photoTypeCode;
    private String photoTypeName;
    private String photoName;
    private String photoPath;
    private String cusNumId;
    private String position;

    public PhotoEntity() {
    }

    public PhotoEntity(Long id) {
        this.id = id;
    }

    public PhotoEntity(Long id, Boolean isBp, String SeqNo, String photoTypeCode, String photoTypeName, String photoName, String photoPath, String cusNumId, String position) {
        this.id = id;
        this.isBp = isBp;
        this.SeqNo = SeqNo;
        this.photoTypeCode = photoTypeCode;
        this.photoTypeName = photoTypeName;
        this.photoName = photoName;
        this.photoPath = photoPath;
        this.cusNumId = cusNumId;
        this.position = position;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsBp() {
        return isBp;
    }

    public void setIsBp(Boolean isBp) {
        this.isBp = isBp;
    }

    public String getSeqNo() {
        return SeqNo;
    }

    public void setSeqNo(String SeqNo) {
        this.SeqNo = SeqNo;
    }

    public String getPhotoTypeCode() {
        return photoTypeCode;
    }

    public void setPhotoTypeCode(String photoTypeCode) {
        this.photoTypeCode = photoTypeCode;
    }

    public String getPhotoTypeName() {
        return photoTypeName;
    }

    public void setPhotoTypeName(String photoTypeName) {
        this.photoTypeName = photoTypeName;
    }

    public String getPhotoName() {
        return photoName;
    }

    public void setPhotoName(String photoName) {
        this.photoName = photoName;
    }

    public String getPhotoPath() {
        return photoPath;
    }

    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    public String getCusNumId() {
        return cusNumId;
    }

    public void setCusNumId(String cusNumId) {
        this.cusNumId = cusNumId;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

}
