package com.guoguang.dkcx.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CODE_LIB.
 */
public class CodeLib {

    private Long id;
    private String CODENO;
    private String ITEMNO;
    private String ITEMNAME;
    private String BANKNO;
    private String SORTNO;
    private String ISINUSE;
    private String ITEMDESCRIBE;
    private String ITEMATTRIBUTE;
    private String RELATIVECODE;
    private String ATTRIBUTE1;
    private String ATTRIBUTE2;
    private String ATTRIBUTE3;
    private String ATTRIBUTE4;
    private String ATTRIBUTE5;
    private String ATTRIBUTE6;
    private String ATTRIBUTE7;
    private String ATTRIBUTE8;
    private String INPUTUSER;
    private String INPUTORG;
    private String INPUTTIME;
    private String UPDATEUSER;
    private String UPDATETIME;
    private String REMARK;
    private String HELPTEXT;

    public CodeLib() {
    }

    public CodeLib(Long id) {
        this.id = id;
    }

    public CodeLib(Long id, String CODENO, String ITEMNO, String ITEMNAME, String BANKNO, String SORTNO, String ISINUSE, String ITEMDESCRIBE, String ITEMATTRIBUTE, String RELATIVECODE, String ATTRIBUTE1, String ATTRIBUTE2, String ATTRIBUTE3, String ATTRIBUTE4, String ATTRIBUTE5, String ATTRIBUTE6, String ATTRIBUTE7, String ATTRIBUTE8, String INPUTUSER, String INPUTORG, String INPUTTIME, String UPDATEUSER, String UPDATETIME, String REMARK, String HELPTEXT) {
        this.id = id;
        this.CODENO = CODENO;
        this.ITEMNO = ITEMNO;
        this.ITEMNAME = ITEMNAME;
        this.BANKNO = BANKNO;
        this.SORTNO = SORTNO;
        this.ISINUSE = ISINUSE;
        this.ITEMDESCRIBE = ITEMDESCRIBE;
        this.ITEMATTRIBUTE = ITEMATTRIBUTE;
        this.RELATIVECODE = RELATIVECODE;
        this.ATTRIBUTE1 = ATTRIBUTE1;
        this.ATTRIBUTE2 = ATTRIBUTE2;
        this.ATTRIBUTE3 = ATTRIBUTE3;
        this.ATTRIBUTE4 = ATTRIBUTE4;
        this.ATTRIBUTE5 = ATTRIBUTE5;
        this.ATTRIBUTE6 = ATTRIBUTE6;
        this.ATTRIBUTE7 = ATTRIBUTE7;
        this.ATTRIBUTE8 = ATTRIBUTE8;
        this.INPUTUSER = INPUTUSER;
        this.INPUTORG = INPUTORG;
        this.INPUTTIME = INPUTTIME;
        this.UPDATEUSER = UPDATEUSER;
        this.UPDATETIME = UPDATETIME;
        this.REMARK = REMARK;
        this.HELPTEXT = HELPTEXT;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCODENO() {
        return CODENO;
    }

    public void setCODENO(String CODENO) {
        this.CODENO = CODENO;
    }

    public String getITEMNO() {
        return ITEMNO;
    }

    public void setITEMNO(String ITEMNO) {
        this.ITEMNO = ITEMNO;
    }

    public String getITEMNAME() {
        return ITEMNAME;
    }

    public void setITEMNAME(String ITEMNAME) {
        this.ITEMNAME = ITEMNAME;
    }

    public String getBANKNO() {
        return BANKNO;
    }

    public void setBANKNO(String BANKNO) {
        this.BANKNO = BANKNO;
    }

    public String getSORTNO() {
        return SORTNO;
    }

    public void setSORTNO(String SORTNO) {
        this.SORTNO = SORTNO;
    }

    public String getISINUSE() {
        return ISINUSE;
    }

    public void setISINUSE(String ISINUSE) {
        this.ISINUSE = ISINUSE;
    }

    public String getITEMDESCRIBE() {
        return ITEMDESCRIBE;
    }

    public void setITEMDESCRIBE(String ITEMDESCRIBE) {
        this.ITEMDESCRIBE = ITEMDESCRIBE;
    }

    public String getITEMATTRIBUTE() {
        return ITEMATTRIBUTE;
    }

    public void setITEMATTRIBUTE(String ITEMATTRIBUTE) {
        this.ITEMATTRIBUTE = ITEMATTRIBUTE;
    }

    public String getRELATIVECODE() {
        return RELATIVECODE;
    }

    public void setRELATIVECODE(String RELATIVECODE) {
        this.RELATIVECODE = RELATIVECODE;
    }

    public String getATTRIBUTE1() {
        return ATTRIBUTE1;
    }

    public void setATTRIBUTE1(String ATTRIBUTE1) {
        this.ATTRIBUTE1 = ATTRIBUTE1;
    }

    public String getATTRIBUTE2() {
        return ATTRIBUTE2;
    }

    public void setATTRIBUTE2(String ATTRIBUTE2) {
        this.ATTRIBUTE2 = ATTRIBUTE2;
    }

    public String getATTRIBUTE3() {
        return ATTRIBUTE3;
    }

    public void setATTRIBUTE3(String ATTRIBUTE3) {
        this.ATTRIBUTE3 = ATTRIBUTE3;
    }

    public String getATTRIBUTE4() {
        return ATTRIBUTE4;
    }

    public void setATTRIBUTE4(String ATTRIBUTE4) {
        this.ATTRIBUTE4 = ATTRIBUTE4;
    }

    public String getATTRIBUTE5() {
        return ATTRIBUTE5;
    }

    public void setATTRIBUTE5(String ATTRIBUTE5) {
        this.ATTRIBUTE5 = ATTRIBUTE5;
    }

    public String getATTRIBUTE6() {
        return ATTRIBUTE6;
    }

    public void setATTRIBUTE6(String ATTRIBUTE6) {
        this.ATTRIBUTE6 = ATTRIBUTE6;
    }

    public String getATTRIBUTE7() {
        return ATTRIBUTE7;
    }

    public void setATTRIBUTE7(String ATTRIBUTE7) {
        this.ATTRIBUTE7 = ATTRIBUTE7;
    }

    public String getATTRIBUTE8() {
        return ATTRIBUTE8;
    }

    public void setATTRIBUTE8(String ATTRIBUTE8) {
        this.ATTRIBUTE8 = ATTRIBUTE8;
    }

    public String getINPUTUSER() {
        return INPUTUSER;
    }

    public void setINPUTUSER(String INPUTUSER) {
        this.INPUTUSER = INPUTUSER;
    }

    public String getINPUTORG() {
        return INPUTORG;
    }

    public void setINPUTORG(String INPUTORG) {
        this.INPUTORG = INPUTORG;
    }

    public String getINPUTTIME() {
        return INPUTTIME;
    }

    public void setINPUTTIME(String INPUTTIME) {
        this.INPUTTIME = INPUTTIME;
    }

    public String getUPDATEUSER() {
        return UPDATEUSER;
    }

    public void setUPDATEUSER(String UPDATEUSER) {
        this.UPDATEUSER = UPDATEUSER;
    }

    public String getUPDATETIME() {
        return UPDATETIME;
    }

    public void setUPDATETIME(String UPDATETIME) {
        this.UPDATETIME = UPDATETIME;
    }

    public String getREMARK() {
        return REMARK;
    }

    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

    public String getHELPTEXT() {
        return HELPTEXT;
    }

    public void setHELPTEXT(String HELPTEXT) {
        this.HELPTEXT = HELPTEXT;
    }

}
