package com.guoguang.khgl.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUS_INFO.
 */
public class CusInfo {

    private Long id;
    private String seqNo;
    private String FullName;
    private String CertType;
    private String InsertTime;
    private String UpdateTime;
    private String CertID;
    private String ManageUserName;
    private String CusInfo;

    public CusInfo() {
    }

    public CusInfo(Long id) {
        this.id = id;
    }

    public CusInfo(Long id, String seqNo, String FullName, String CertType, String InsertTime, String UpdateTime, String CertID, String ManageUserName, String CusInfo) {
        this.id = id;
        this.seqNo = seqNo;
        this.FullName = FullName;
        this.CertType = CertType;
        this.InsertTime = InsertTime;
        this.UpdateTime = UpdateTime;
        this.CertID = CertID;
        this.ManageUserName = ManageUserName;
        this.CusInfo = CusInfo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSeqNo() {
        return seqNo;
    }

    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    public String getFullName() {
        return FullName;
    }

    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    public String getCertType() {
        return CertType;
    }

    public void setCertType(String CertType) {
        this.CertType = CertType;
    }

    public String getInsertTime() {
        return InsertTime;
    }

    public void setInsertTime(String InsertTime) {
        this.InsertTime = InsertTime;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getCertID() {
        return CertID;
    }

    public void setCertID(String CertID) {
        this.CertID = CertID;
    }

    public String getManageUserName() {
        return ManageUserName;
    }

    public void setManageUserName(String ManageUserName) {
        this.ManageUserName = ManageUserName;
    }

    public String getCusInfo() {
        return CusInfo;
    }

    public void setCusInfo(String CusInfo) {
        this.CusInfo = CusInfo;
    }

}
