package com.guoguang.khgl.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig codeLibDaoConfig;
    private final DaoConfig areaLibDaoConfig;
    private final DaoConfig cusInfoDaoConfig;

    private final CodeLibDao codeLibDao;
    private final AreaLibDao areaLibDao;
    private final CusInfoDao cusInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        codeLibDaoConfig = daoConfigMap.get(CodeLibDao.class).clone();
        codeLibDaoConfig.initIdentityScope(type);

        areaLibDaoConfig = daoConfigMap.get(AreaLibDao.class).clone();
        areaLibDaoConfig.initIdentityScope(type);

        cusInfoDaoConfig = daoConfigMap.get(CusInfoDao.class).clone();
        cusInfoDaoConfig.initIdentityScope(type);

        codeLibDao = new CodeLibDao(codeLibDaoConfig, this);
        areaLibDao = new AreaLibDao(areaLibDaoConfig, this);
        cusInfoDao = new CusInfoDao(cusInfoDaoConfig, this);

        registerDao(CodeLib.class, codeLibDao);
        registerDao(AreaLib.class, areaLibDao);
        registerDao(CusInfo.class, cusInfoDao);
    }
    
    public void clear() {
        codeLibDaoConfig.getIdentityScope().clear();
        areaLibDaoConfig.getIdentityScope().clear();
        cusInfoDaoConfig.getIdentityScope().clear();
    }

    public CodeLibDao getCodeLibDao() {
        return codeLibDao;
    }

    public AreaLibDao getAreaLibDao() {
        return areaLibDao;
    }

    public CusInfoDao getCusInfoDao() {
        return cusInfoDao;
    }

}
